name: Copilot Metrics Retention

on:
  workflow_dispatch:
    inputs:
      org_name: 
        description: 'Organization name'
        required: true
        default: 'octodemo'
      json_path:
        description: 'JSON File path'
        required: true
        default: 'metrics.json'

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copilot Metrics Retention 
        uses: ambilykk/copilot-metrics-retention@main
        with:        
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
          org_name: ${{ inputs.org_name }} 
          json_path: ${{ inputs.json_path }} 

      - name: Commit and push if it changed
        run: |
          git config --global user.name 'Copilot Metrics Retention'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Copilot Metrics data update"
          git push
